project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('reading_log.urls')),
    path("accounts/", include("accounts.urls")),
]

reading_log/urls.py
from django.urls import path
from . import views

app_name = 'reading_log'

urlpatterns = [
    #path('', views.ReadingLogList.as_view(), name='reading_log_list'),
    path('', views.UserGuide.as_view(), name='user_guide'),
    path('book_create', views.BookCreate.as_view(), name='book_create'),
    path('reading_log_create', views.ReadingLogCreate.as_view(), name='reading_log_create'),
    path('reading_log_update/<int:pk>', views.ReadingLogUpdate.as_view(), name='reading_log_update'),
    path('reading_log_delete/<int:pk>', views.ReadingLogDelete.as_view(), name='reading_log_delete'),
    path('individual_log/<int:user_id>', views.IndividualLog.as_view(), name='individual_log'),
    path('dashboard/<int:user_id>', views.Dashboard.as_view(), name='dashboard'),
]

reading_log/models.py
from django.db import models
from django.conf import settings
from taggit.managers import TaggableManager


class Book(models.Model):
    title = models.CharField("タイトル", max_length=128)
    author = models.CharField("著者", max_length=128)
    pages = models.IntegerField("ページ数", blank=True)
    price = models.IntegerField("価格", blank=True)
    tags = TaggableManager(blank=True)

    def __str__(self):
        return self.title


class BookStatus(models.Model):
    status = models.CharField("状態", max_length=32)

    def __str__(self):
        return self.status


class ReadingLog(models.Model):
    book = models.ForeignKey(Book, on_delete=models.PROTECT, verbose_name="書籍")
    description = models.TextField("説明", blank=True)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL,
                                   verbose_name="投稿者",
                                   on_delete=models.CASCADE)
    status = models.ForeignKey(BookStatus, on_delete=models.PROTECT, verbose_name="状態")
    finish_date = models.DateField("読了日", blank=True, null=True)
    is_public = models.BooleanField("公開する", default=True)

    def __str__(self):
        return self.book.title

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=["book", "created_by"],
                name="book_created_by_unique"
            ),
        ]

reading_log/forms.py
from django import forms
from .models import Book, BookStatus, ReadingLog
from django.utils import timezone
from taggit.models import Tag
from .widgets import CustomRadioSelect
from django.db.models import Count


class ReadingLogSearchForm(forms.Form):
    # 年の選択肢を動的に作る
    start_year = 2019  # 家計簿の登録を始めた年
    end_year = timezone.now().year  # 現在の年
    years = [(year, f"{year}年") for year in reversed(range(start_year, end_year + 1))]
    years.insert(0, (0, ""))  # 空白の選択を追加
    YEAR_CHOICES = tuple(years)

    # 月の選択肢を動的に作る
    months = [(month, f"{month}月") for month in range(1, 13)]
    months.insert(0, (0, ""))
    MONTH_CHOICES = tuple(months)

    # 年の選択
    year = forms.ChoiceField(
        label="年での絞り込み",
        required=False,
        choices=YEAR_CHOICES,
        widget=forms.Select(attrs={"class": "form"})
    )

    # 月の選択
    month = forms.ChoiceField(
        label="月での絞り込み",
        required=False,
        choices=MONTH_CHOICES,
        widget=forms.Select(attrs={"class": "form"})
    )

    # キーワード
    key_word = forms.CharField(
        label="検索キーワード",
        required=False,
        widget=forms.TextInput(attrs={"class": "form",
                                      "autocomplete": "off",
                                      "placeholder": "書籍・著者・摘要",
                                      })
    )

    # 登録件数が多い順に、件数1以上のタグのみ表示
    # TODO: 指定ユーザのみ、かつ指定ユーザが登録しているログのみカウント対象としたい
    tag_queryset = Tag.objects.all()
    tag_queryset = tag_queryset.annotate(log_count=Count("taggit_taggeditem_items")).filter(log_count__gt=0).order_by("-log_count")
    #MAX_TAG_DISPLAY_NUM = 10
    #if tag_queryset.count() > MAX_TAG_DISPLAY_NUM:
    #    tag_queryset = tag_queryset[:MAX_TAG_DISPLAY_NUM]
    # カテゴリー検索
    tag = forms.ModelChoiceField(
        label="タグでの絞り込み",
        required=False,
        queryset=tag_queryset,
        widget=CustomRadioSelect
    )


class BookCreateForm(forms.ModelForm):
    tags = forms.ModelMultipleChoiceField(queryset=Tag.objects.all(),
                                          widget=forms.CheckboxSelectMultiple())

    class Meta:
        model = Book
        fields = "__all__"

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs["class"] = "form"
            field.widget.attrs["placeholder"] = field.label
            field.widget.attrs["autocomplete"] = "off"


class ReadingLogCreateForm(forms.ModelForm):
    class Meta:
        model = ReadingLog
        fields = ["book", "description", "status", "finish_date", "is_public"]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs["class"] = "form"
            field.widget.attrs["placeholder"] = field.label
            field.widget.attrs["autocomplete"] = "off"

reading_log/views.py
from django.views import generic
from .models import Book, ReadingLog
from .forms import ReadingLogSearchForm, ReadingLogCreateForm, BookCreateForm
from django.db.models import Q
from django.urls import reverse_lazy
from django.db import IntegrityError
from django.contrib import messages
from django.shortcuts import redirect
from django.core.paginator import Page
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import get_user_model
from django.http import Http404
import numpy as np
import pandas as pd
from django_pandas.io import read_frame
from .plugin_plotly import GraphGenerator
from django.db.models import Sum


class UserGuide(generic.TemplateView):
    template_name = "reading_log/user_guide.html"

    def get_success_url(self):
        return reverse_lazy("reading_log:individual_log", args=[self.request.user.id])

    def get(self, request, *args, **kwargs):
        if self.request.user.is_authenticated:
            return redirect(self.get_success_url())
        return super().get(request, *args, **kwargs)


class BookCreate(LoginRequiredMixin, generic.CreateView):
    template_name = "reading_log/register.html"
    model = Book
    form_class = BookCreateForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["page_title"] = "書籍登録"
        return context

    def get_success_url(self):
        #return reverse_lazy("reading_log:reading_log_list")
        return reverse_lazy("reading_log:individual_log", args=[self.request.user.id])


class ReadingLogCreate(LoginRequiredMixin, generic.CreateView):
    template_name = "reading_log/register.html"
    model = ReadingLog
    form_class = ReadingLogCreateForm

    # ログインユーザの情報を設定する
    def form_valid(self, form):
        try:
            self.object = reading_log = form.save(commit=False)
            self.object.created_by = self.request.user
            self.object.save()
            messages.info(self.request,
                          f"書籍\"{reading_log.book}\"を登録しました")
            return super().form_valid(form)
        except IntegrityError:
            messages.error(self.request,
                           f"書籍\"{reading_log.book}\"のログは登録済みです")
            return super().form_invalid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["page_title"] = "読書ログ登録"
        return context

    def get_success_url(self):
        #return reverse_lazy("reading_log:reading_log_list")
        return reverse_lazy("reading_log:individual_log", args=[self.request.user.id])


class ReadingLogUpdate(LoginRequiredMixin, generic.UpdateView):
    template_name = "reading_log/register.html"
    model = ReadingLog
    form_class = ReadingLogCreateForm

    def form_valid(self, form):
        try:
            self.object = reading_log = form.save(commit=False)
            self.object.created_by = self.request.user
            self.object.save()
            messages.info(self.request,
                          f"書籍\"{reading_log.book}\"を更新しました")
            return super().form_valid(form)
        except IntegrityError:
            messages.error(self.request,
                           f"書籍\"{reading_log.book}\"のログは登録済みです")
            return super().form_invalid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["page_title"] = "読書ログ更新"
        return context

    def get_success_url(self):
        #return reverse_lazy("reading_log:reading_log_list")
        return reverse_lazy("reading_log:individual_log", args=[self.request.user.id])


class ReadingLogDelete(LoginRequiredMixin, generic.DeleteView):
    template_name = "reading_log/delete.html"
    model = ReadingLog

    def get_success_url(self):
        #return reverse_lazy("reading_log:reading_log_list")
        return reverse_lazy("reading_log:individual_log", args=[self.request.user.id])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["page_title"] = "読書ログ削除確認"

        return context

    def delete(self, request, *args, **kwargs):
        self.object = reading_log = self.get_object()

        reading_log.delete()
        messages.info(self.request,
                      f"読書ログ\"{reading_log.book}\"を削除しました")
        return redirect(self.get_success_url())


class IndividualLog(LoginRequiredMixin, generic.ListView):
    template_name = "reading_log/individual_log.html"
    model = ReadingLog
    ordering = "book"
    context_object_name = "reading_log_list"
    paginate_by = 10
    pk_url_kwarg = "user_id"

    def get_queryset(self):
        page_user_id = self.kwargs.get("user_id")
        # 存在しないユーザのURLは404エラーを返す
        if not get_user_model().objects.filter(id=page_user_id).exists():
            raise Http404

        # ページユーザIDと一致するログのみ表示し、ログインユーザでなければ閲覧できない
        queryset = super().get_queryset()
        if self.request.user.is_authenticated:
            if self.request.user.id == page_user_id:
                queryset = queryset.filter(created_by=page_user_id)
            else:
                queryset = queryset.filter(created_by=page_user_id, is_public=True)
        else:
            raise Http404
        self.form = form = ReadingLogSearchForm(self.request.GET or None)

        if form.is_valid():
            year = form.cleaned_data.get("year")
            # 何も選択されていないときは0の文字列が入るため、除外
            if year and year != "0":
                queryset = queryset.filter(finish_date__year=year)

            # 何も選択されていないときは0の文字列が入るため、除外
            month = form.cleaned_data.get("month")
            if month and month != "0":
                queryset = queryset.filter(finish_date__month=month)

            # キーワードの絞り込み
            key_word = form.cleaned_data.get("key_word")
            if key_word:
                for word in key_word.split():
                    queryset = queryset.filter(
                        Q(description__icontains=word) |
                        Q(book__author__icontains=word) |
                        Q(book__title__icontains=word)).distinct()

            tag = form.cleaned_data.get("tag")
            if tag:
                queryset = queryset.filter(book__tags=tag)

        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        page_user_id = self.kwargs.get("user_id")
        page_user_name = get_user_model().objects.get(id=page_user_id).username
        print(f"page_user_id: {page_user_id}")
        print(f"page_user_name: {page_user_name}")
        context["page_user_id"] = page_user_id
        context["page_user_name"] = page_user_name
        context["search_form"] = self.form
        page: Page = context["page_obj"]
        # get_elided_page_rangeの結果を、paginator_range変数から使用可能
        context["paginator_range"] = page.paginator.get_elided_page_range(
            page.number,
            on_each_side=2,
            on_ends=1
        )

        return context


def pages2height_in_meter(num_of_pages):
    height_in_meter = num_of_pages * 0.6 * 1e-4  # 0.6 mm換算
    return round(height_in_meter, 2)


def get_height_indicator(height_in_meter):
    if 0.002 <= height_in_meter < 0.03:
        return "ミジンコ(2 mm)"
    if 0.03 <= height_in_meter < 0.08:
        return "メダカ(3 cm)"
    if 0.08 <= height_in_meter < 0.24:
        return "ハツカネズミ(8 cm)"
    elif 0.24 <= height_in_meter < 0.40:
        return "猫(24 cm)"
    elif 0.40 <= height_in_meter < 1.0:
        return "柴犬(40 cm)"
    elif 1.0 <= height_in_meter < 1.7:
        return "ニホンジカ(1 m)"
    elif 1.7 <= height_in_meter < 2.8:
        return "ホモサピエンス(1.7 m)"
    elif 2.8 <= height_in_meter < 4.53:
        return "インドゾウ(2.8 m)"
    elif 4.53 <= height_in_meter < 10:
        return "天保山(4.53 m)"
    elif 10 <= height_in_meter < 18:
        return "ジンベエザメ(10 m)"
    elif 18 <= height_in_meter < 28:
        return "ガンダム(18 m)"
    elif 28 <= height_in_meter < 131.0:
        return "シロナガスクジラ(28 m)"
    elif 131 <= height_in_meter < 300.0:
        return "京都タワー(131 m)"
    elif 300.0 <= height_in_meter < 634.0:
        return "あべのハルカス(300 m)"
    elif 634.0 <= height_in_meter < 830:
        return "東京スカイツリー(634 m)"
    elif 830 <= height_in_meter < 1337:
        return "ブルジュ・ハリファ(830 m)"
    elif 1377 <= height_in_meter < 1915:
        return "伊吹山(1377 m)"
    elif 1915 <= height_in_meter < 3776:
        return "八経ヶ岳(1915 m)"
    elif 3776 <= height_in_meter < 4478:
        return "富士山(3776 m)"
    elif 4478 <= height_in_meter < 5895:
        return "マッターホルン(4478 m)"
    elif 5895 <= height_in_meter < 8849:
        return "キリマンジャロ(5895 m)"
    elif 8849 <= height_in_meter:
        return "エベレスト(8849 m)"


def make_message(reading_log_queryset, book_status):
    book_queryset = reading_log_queryset.filter(status__status__contains=book_status)
    num_of_pages = book_queryset.aggregate(total_count=Sum("book__pages"))["total_count"]
    height_in_meter = pages2height_in_meter(num_of_pages)
    pages_indicator = get_height_indicator(height_in_meter)
    message = f"{book_status}本の高さ: {height_in_meter} m\n{pages_indicator}の大きさを超えています"
    return message


class Dashboard(LoginRequiredMixin, generic.TemplateView):
    template_name = "reading_log/dashboard.html"
    pk_url_kwarg = "user_id"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        page_user_id = self.kwargs.get("user_id")
        page_user_name = get_user_model().objects.get(id=page_user_id).username
        context["page_user_id"] = page_user_id
        context["page_user_name"] = page_user_name

        reading_log_queryset = ReadingLog.objects.all()
        if self.request.user.is_authenticated:
            if self.request.user.id == page_user_id:
                reading_log_queryset = reading_log_queryset.filter(created_by=page_user_id)
            else:

reading_log/templates/reading_log/book_detail.html
{% extends "base.html" %}

{% block content %}

<div class="my-5">
  <div class="row">
    <div class="col-md-6 text-center">
      <img src="{{ book_data.image }}" alt="{{ book_data.title }}" loading="lazy">
    </div>

    <div class="col-md-6">
      <div class="card">
        <div class="card-body px-2 py-1">
          <div class="p-4">
            <h3>タイトル：{{ book_data.title }}</h3>
            <h3>著者：{{ book_data.author }}</h3>
            <hr>
            <form method="POST">
              {% csrf_token %}
              {{ form }}
              <button class="btn btn-primary btn-lg mt-4" type="submit" name="button">書籍追加</button>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
  <br>

  {% if book_data.itemCaption %}
    <div class="mb-5">
      <h3>概要</h3>
      <hr>
      <p>{{ book_data.itemCaption }}</p>
    </div>
  {% endif %}

  <div class="mb-5">
    <h3>情報</h3>
    <hr>
    <p>発売日：{{ book_data.salesDate }}</p>
    <p>価格：{{ book_data.price }}円</p>
    <p>出版社：{{ book_data.publisherName }}</p>
    <p>発行形式：{{ book_data.size }}</p>
    <p>ISBN-10：{{ book_data.isbn }}</p>
  </div>
</div>

{% endblock %}

reading_log/templates/reading_log/book_search.html
{% extends "base.html" %}

{% block content %}

<h1>追加したい書籍を検索してください</h1>
<form method="post">
  {% csrf_token %}
  {% for field in form %}
  <div class="mt-4">
    {{ field.label }}
    {{ field }}
  </div>
  {% endfor %}
  <button class="btn btn-primary btn-lg mt-4" type="submit" name="button">検索</button>
</form>

{% endblock %}

reading_log/templates/reading_log/dashboard.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% load reading_log %}

{% block content %}

<ul class="list-group mb-4">
  <li class="list-group-item"> {{ page_user_name }}さんのダッシュボード </li>
</ul>

<div class="alert alert-primary">
  {{ finished_message | linebreaksbr }}
</div>
<div class="alert alert-secondary">
  {{ stacked_message | linebreaksbr }}
</div>

{% autoescape off %}
{{ transition_plot }}
{% endautoescape %}

{% endblock %}

{% block extrajs %}
<script src="https://cdn.plot.ly/plotly-latest.min.js"></script>

{% endblock %}

reading_log/templates/reading_log/delete.html
{% extends "base.html" %}

{% block content %}
<h1>{{ page_title }}</h1>
<p class="mt-5"> 本当に削除してよろしいですか？</p>

<p class="mt-4">書籍：{{ object.book }}</p>
<p class="mt-4">状態：{{ object.status }}</p>
<p class="mt-4">摘要： {% if object.description %}{{ object.description }}{% endif %}</p>

<form class="mt-4" method="post">
  {% csrf_token %}
  <a class="btn btn-primary btn-lg" href="{% url 'reading_log:individual_log' user.id %}">
    いいえ、一覧に戻ります
  </a>
  <button type="submit" class="btn btn-danger btn-lg">
    はい、削除します
  </button>
</form>

{% endblock %}

reading_log/templates/reading_log/individual_log.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% load reading_log %}

{% block content %}

<ul class="list-group mb-4">
  <li class="list-group-item"> {{ page_user_name }}さんの読書ログ </li>
</ul>

<form class="mt-2" id="search-form" action="" method="GET">
  <div>
    <label class="label mr-4">年月</label>
    {{ search_form.year }}
    {{ search_form.month }}
  </div>

  <div class="mt-4">
    {{ search_form.key_word }}
    <button class="btn btn-primary btn-lg" type="submit">検索</button>
  </div>
  <div class="mt-2 inline">
    {{ search_form.tag }}
  </div>
</form>

<p class="search-result mt-3"> {{ page_obj.paginator.count }}件の検索結果 </p>

<!-- 一覧表示 -->
<table class="table mt-3">
  <tr>
    <th>書籍</th>
    <th>著者</th>
    <th>状態</th>
    <th>読了月</th>
    <th>タグ</th>
    {% if user.is_authenticated and page_user_id == user.id %}
    <th>編集</th>
    {% endif %}
  </tr>
  {% for reading_log in reading_log_list %}

  <tr>
    <td>{{ reading_log.book.title }}</td>
    <td>{{ reading_log.book.author }}</td>
    <td>{{ reading_log.status }}</td>
    <td>
      {% if reading_log.finish_date %}
      {{ reading_log.finish_date|date:"Y年m月" }}
      {% endif %}
    </td>
    <td>
      {% if reading_log.book.tags.names %}
        {% for tag in reading_log.book.tags.names %}
          {% if forloop.last %}
            {{ tag }}
          {% else %}
            {{ tag }},
          {% endif %}
        {% endfor %}
      {% endif %}
    </td>
    {% if user.is_authenticated and page_user_id == user.id %}
    <td>
      <div class="manage-btn-area">
        <div class="update-btn-area">
          <a class="btn btn-outline-primary btn-lg" href="{% url 'reading_log:reading_log_update' reading_log.pk %}">更新</a>
        </div>
        <div class="delete-btn-area">
          <a class="btn btn-outline-danger btn-lg" href="{% url 'reading_log:reading_log_delete' reading_log.pk %}">削除</a>
        </div>
      </div>
    </td>
    {% endif %}
  </tr>
  {% endfor %}
</table>

<!-- ページネーション -->
{% if is_paginated %}
<ul class="pagination pagination-lg justify-content-center mt-5">
  {% for i in paginator_range %}
    {% if page_obj.number == i %}
      <li class="active page-item">
        <span class="page-link">{{ i }}</span>
      </li>
    {% else %}
      {% if i == paginator.ELLIPSIS %}
        <li class="page-item">
          <span class="page-link">{{ paginator.ELLIPSIS }}</span>
        </li>
      {% else %}
        <li class="page-item">
          <a class="page-link" href="?page={{ i }}">{{ i }}</a>
        </li>
      {% endif %}
    {% endif %}
  {% endfor %}
</ul>
{% endif %}


{% endblock %}

{% block extrajs %}
<script type="text/javascript">
  document.addEventListener('DOMContentLoaded', e => {
    const searchForm = document.getElementById('search-form');

    //タグがクリックされたら検索実行
    for (const check of document.getElementsByName('tag')) {
      check.addEventListener('change', () => {
        searchForm.submit();
      });
    }

    // 選択済みのタグがクリックされたらチェックを解除して検索実行
    const selectedTag = document.querySelector(`input[name='tag']:checked`)
    if (selectedTag) {
      selectedTag.onclick = () => {
        selectedTag.checked = false
        searchForm.submit();
      }
    }
  });
</script>
{% endblock %}

reading_log/templates/reading_log/reading_log_list.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% load reading_log %}

{% block content %}

<form class="mt-2" id="search-form" action="" method="GET">
  <div>
    <label class="label mr-4">年月</label>
    {{ search_form.year }}
    {{ search_form.month }}
  </div>

  <div class="mt-4">
    {{ search_form.key_word }}
    <button class="btn btn-primary btn-lg" type="submit">検索</button>
  </div>
  <div class="mt-2 inline">
    {{ search_form.tag }}
  </div>
</form>

<p class="search-result mt-3"> {{ page_obj.paginator.count }}件の検索結果 </p>

<!-- 一覧表示 -->
<table class="table mt-3">
  <tr>
    <th>書籍</th>
    <th>著者</th>
    <th>状態</th>
    <th>読了月</th>
    <th>タグ</th>
    <th>編集</th>
  </tr>
  {% for reading_log in reading_log_list %}

  <tr>
    <td>{{ reading_log.book.title }}</td>
    <td>{{ reading_log.book.author }}</td>
    <td>{{ reading_log.status }}</td>
    <td>
      {% if reading_log.finish_date %}
      {{ reading_log.finish_date|date:"Y年m月" }}
      {% endif %}
    </td>
    <td>
      {% if reading_log.book.tags.names %}
        {% for tag in reading_log.book.tags.names %}
          {% if forloop.last %}
            {{ tag }}
          {% else %}
            {{ tag }},
          {% endif %}
        {% endfor %}
      {% endif %}
    </td>
    {% if user.is_authenticated and reading_log.created_by_id == user.id %}
    <td>
      <div class="manage-btn-area">
        <div class="update-btn-area">
          <a class="btn btn-outline-primary btn-lg" href="{% url 'reading_log:reading_log_update' reading_log.pk %}">更新</a>
        </div>
        <div class="delete-btn-area">
          <a class="btn btn-outline-danger btn-lg" href="{% url 'reading_log:reading_log_delete' reading_log.pk %}">削除</a>
        </div>
      </div>
    </td>
    {% endif %}
  </tr>
  {% endfor %}
</table>

<!-- ページネーション -->
{% if is_paginated %}
<ul class="pagination pagination-lg justify-content-center mt-5">
  {% for i in paginator_range %}
    {% if page_obj.number == i %}
      <li class="active page-item">
        <span class="page-link">{{ i }}</span>
      </li>
    {% else %}
      {% if i == paginator.ELLIPSIS %}
        <li class="page-item">
          <span class="page-link">{{ paginator.ELLIPSIS }}</span>
        </li>
      {% else %}
        <li class="page-item">
          <a class="page-link" href="?page={{ i }}">{{ i }}</a>
        </li>
      {% endif %}
    {% endif %}
  {% endfor %}
</ul>
{% endif %}


{% endblock %}

{% block extrajs %}
<script type="text/javascript">
  document.addEventListener('DOMContentLoaded', e => {
    const searchForm = document.getElementById('search-form');

    //タグがクリックされたら検索実行
    for (const check of document.getElementsByName('tag')) {
      check.addEventListener('change', () => {
        searchForm.submit();
      });
    }

    // 選択済みのタグがクリックされたらチェックを解除して検索実行
    const selectedTag = document.querySelector(`input[name='tag']:checked`)
    if (selectedTag) {
      selectedTag.onclick = () => {
        selectedTag.checked = false
        searchForm.submit();
      }
    }
  });
</script>
{% endblock %}

reading_log/templates/reading_log/register.html
{% extends "base.html" %}

{% block content %}
<h1>{{ page_title }}</h1>
<form method="POST">
  {% csrf_token %}
  {{ form.non_field_errors }}
  {% for field in form %}
  <div class="mt-4">
    {{ field.label }}
    {{ field }}
    {{ field.errors }}
  </div>
  {% endfor %}
  <button class="btn btn-primary btn-lg mt-4" type="submit" name="button">送信</button>
</form>

<!-- date picker -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/themes/base/jquery-ui.min.css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
<script type="text/javascript">
  $(function() {
    $('#id_finish_date').datepicker({
      dateFormat: 'yy-mm-dd',
      firstDay: 1,
      dayNamesMin: ["日", "月", "火", "水", "木", "金", "土"],
      monthNames: ["1月", "2月", "3月", "4月", "5月", "6月", "7月", "8月", "9月", "10月", "11月", "12月"],
    });
  })
</script>

{% endblock %}

reading_log/templates/reading_log/search_results.html
{% extends "base.html" %}

{% block content %}

<div class="text-center my-5">
  <div class="mb-5">
    <p class="search-result mt-3"> 「{{ key_word }}」の検索結果 </p>
  </div>
  <div class="row">
    {% for book in book_data %}
      <div class="col-3 mb-4">
        <div class="card img-thumbnail booklist h-100">
          <a href="{% url 'reading_log:book_detail' book.isbn %}">
            <img class="card-img-top card-thum" src="{{ book.image }}" alt="{{ book.title }}" loading="lazy">
          </a>
          <div class="card-body text-center px-2 py-3">
            <h4 class="font-weight-bold">{{ book.title }}</h4>
          </div>
        </div>
      </div>
    {% empty %}
      <p>該当するものはありません</p>
    {% endfor %}
  </div>
</div>

{% endblock %}

reading_log/templates/reading_log/user_guide.html
{% extends "base.html" %}

{% block content %}

ログインしてください。

{% endblock %}